name: Build and Deploy Python App (Windows)

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거

jobs:
  build-and-deploy:
    runs-on: windows-latest  # Windows 환경에서 실행

    steps:
      # 코드 체크아웃
      - name: Check out code
        uses: actions/checkout@v3

      # Python 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 필요한 Python 버전

      # 의존성 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 프로젝트 의존성 설치

      # 애플리케이션 빌드 (PyInstaller 사용)
      - name: Build executable
        run: |
          pip install pyinstaller  # PyInstaller 설치
          pyinstaller --onefile --windowed my_app.py  # 빌드 명령어

      # 빌드된 파일을 Artifacts로 업로드
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-python-app
          path: dist/my_app.exe  # 빌드된 파일 경로

